#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/trainingapp_local
#    username:
#    password:
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
