spring:
  application:
    # pulled from SPRING_APPLICATION_NAME (default “main-microservice”)
    name: ${SPRING_APPLICATION_NAME:main-microservice}

  profiles:
    # pulled from SPRING_PROFILES_ACTIVE (default “local”)
    active: ${SPRING_PROFILES_ACTIVE:local}

  kafka:
    # pulled from SPRING_KAFKA_BOOTSTRAP_SERVERS (default “kafka:9092”)
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: training-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

  datasource:
    # pulled from SPRING_DATASOURCE_URL / USERNAME / PASSWORD
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/trainingapp}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  doc:
    api-docs:
      enabled: true
    swagger-ui:
      enabled: true

server:
  # pulled from SERVER_PORT (default 8081)
  port: ${SERVER_PORT:8081}

management:
  security:
    enabled: false
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
    shutdown:
      enabled: true
    info:
      env:
        enabled: true
      enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus, metrics, info, health, shutdown, beans

jwt:
  secret: "SOVhpdiDzs659O9ZiK2k+QTlt/Qf4fkHpQRdnn5/0FI="

eureka:
  client:
    # pulled from EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
    register-with-eureka: ${EUREKA_CLIENT_REGISTER-WITH-EUREKA:false}
    fetch-registry:     ${EUREKA_CLIENT_FETCH-REGISTRY:false}
    enabled: false

kafka:
  topic:
    workload: trainer-workload-topic
