server.port=8082

# Eureka configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
spring.application.name=trainer-workload-microservice

jwt.secret =SOVhpdiDzs659O9ZiK2k+QTlt/Qf4fkHpQRdnn5/0FI=
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
