server.port=8082

# Eureka configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
spring.application.name=trainer-workload-microservice
jwt.secret=SOVhpdiDzs659O9ZiK2k+QTlt/Qf4fkHpQRdnn5/0FI=
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Kafka consumer configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=trainer-workload-group

# Use ErrorHandlingDeserializer to better handle deserialization errors
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer

# Trust all packages
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# **Ignore the type headers** from the producer
spring.kafka.consumer.properties.spring.json.use.type.headers=false

# Set the default type to local DTO package
spring.kafka.consumer.properties.spring.json.value.default.type=com.trainingapp.microservice.dto.TrainerWorkloadRequest

# Topic configuration
kafka.topic.workload=trainer-workload-topic
